apiVersion: apps/v1
kind: Deployment
metadata:
  name: @APPNAME@
  labels:
    app: @APPNAME@
spec:
  replicas: 2
  selector:
    matchLabels:
      app: @APPNAME@
  template:
    metadata:
      labels:
        app: @APPNAME@
    spec:
      containers:
        - name: @APPNAME@
          image: @IMAGE_NAME@