apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam
  labels:
    app: notejam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      containers:
        - name: notejam
          image: @IMAGE_NAME@